services:
  pleasure-plays-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: pleasure-plays-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:

# Connection String => Server=localhost,1433;Database=PleasurePlaysDatabase;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True
# docker compose -f .\projects\EntityFramework\docker-compose.yaml up -d

# dotnet ef migrations add InitialCreate
# dotnet ef database update